django_app/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'final_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^prof_rater/', include('prof_rater.urls')),
)

prof_rater/urls.py
from django.conf.urls import patterns, include, url
from prof_rater import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<prof_id>[0-9]+)/$', views.profile, name='profile'),
    url(r'^(?P<prof_id>[0-9]+)/review/$', views.review, name='review'),
    url(r'^(?P<prof_id>[0-9]+)/rate/$', views.create_review, name='rate'),

    url(r'^(?P<dept_code>[A-z]{3,4})/$', views.department, name='department'),
    #url(r'^department/(?P<dept_code>[A-z]{3,4})/$', views.department, name='department'),

    url(r'^(?P<dept_code>[A-z]{3,4})/(?P<course_num>[0-9]{3})/$', views.course, name='course'),
    
    url(r'^(?P<dept_code>[A-z]{3,4})/(?P<course_num>[0-9]{3})/(?P<prof_id>[0-9]+)/$', views.profile_from_course, name='profile_from_course'),
        
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

prof_rater/models.py
import datetime
from django import forms
from django.db import models

# Create your models here.

class Department(models.Model):
    code = models.CharField(max_length=4, default='DEPT')   #CMPT
    name = models.CharField(max_length=200, default='Department Name') #Computing Science
    def __str__(self):
        return self.code + ": "+self.name

class Course(models.Model):
    subject = models.CharField(max_length=4, default='SUBJ') #CMPT
    number  = models.IntegerField(range(100, 999), default=999) #470 
    title = models.CharField(max_length=50) #Web-based Information Systems
    meta_score = models.DecimalField(max_digits=2, decimal_places=1, default=0)    #will be generated on the fly
    def __str__(self):
        return self.subject + " " + str(self.number) + ": " + self.title

class Professor(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    department = models.ForeignKey(Department)
    meta_score = models.DecimalField(max_digits=2, decimal_places=1)
    def __str__(self):
        return self.first_name + " " + self.last_name

class Review(models.Model):
    professor = models.ForeignKey(Professor)
    comments = models.CharField(max_length=350)
    interest_in_course = models.DecimalField(max_digits=2, decimal_places=1)
    course_subject = models.CharField(max_length=4, default='SUBJ') #CMPT
    course_number = models.IntegerField(range(100, 999), default=999) #470  
    #date_published = models.DateTimeField('date published', default=datetime.date.today())
    date_published = models.DateTimeField(("Date published"), auto_now_add = True)
    final_score = models.DecimalField(max_digits=2, decimal_places=1)

    def __str__(self):
        return "["+self.course_subject+" "+str(self.course_number)+"] anonymous review for "+str(self.professor)+":  " + self.comments + ""

class WordCloud(models.Model):
    professor = models.ForeignKey(Professor)
    phrase_one = models.CharField(max_length=20, default='')
    phrase_two = models.CharField(max_length=20, default='')
    phrase_three = models.CharField(max_length=20, default='')

    def __str__(self):
        return "Word cloud entry for "+ str(self.professor)

prof_rater/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from prof_rater.models import Department, Professor, Review, Course, WordCloud
from django.views import generic
from django.utils import timezone
from django.core.urlresolvers import reverse

# Create your views here.


#index page will have the search input form and display results on the same page
def index(request):
    return render(request, 'prof_rater/index.html', {
        'prof_list' : get_prof_list(),
        'course_list' : get_course_list(),
        'dept_list' : get_dept_list(),
    })

#
def department(request, dept_code):
    dept = ''
    try:
        dept = get_object_or_404(Department, code=dept_code.upper()+'')
        try:
            course_list = get_course_list()
            for i in range(len(course_list)-1,-1,-1):
                if(course_list[i].subject.upper() != dept_code.upper()):
                    course_list[i].subject = 'DELETE'
                    course_list.pop(i)
            return render(request, 'prof_rater/department.html', {
                'dept': dept,
                'course_list': course_list,
            })
        except Exception as e:
            return render(request, 'prof_rater/department.html', {'message' : "This department "+dept_code+" has no course. ",})
    except Exception as e:
        return render(request, 'prof_rater/department.html', {'message' : ""+dept_code + " is not a valid department code.",})


# 
def course(request, dept_code, course_num):   
    prof_list = get_prof_list_by_course(dept_code.upper(), course_num)
    for prof in prof_list:
        prof.meta_score = calculate_metascore(prof.id)
        prof.review_set_count = len(Review.objects.filter(course_subject=dept_code)
                                                  .filter(course_number=course_num)
                                                  .filter(professor=prof))
    return render(request, 'prof_rater/course.html', {
        'h1': dept_code + str(course_num),
        'prof_list': prof_list,
    }) 


# professor's profile wil have name of prof and the reviews for him/her and his meta score
def profile(request, prof_id):
        professor = get_object_or_404(Professor, pk=prof_id)
        meta_score = calculate_metascore(prof_id)
        return render(request, 'prof_rater/profile.html', {
        'professor' : professor,
                'meta_score': meta_score,
        'word_cloud_entries': get_word_cloud_entries(prof_id),
    })

# access profile from the course page
def profile_from_course(request, dept_code, course_num, prof_id):
    #profile(request, prof_id)
        professor = get_object_or_404(Professor, pk=prof_id)
        meta_score = calculate_metascore(prof_id)
        return render(request, 'prof_rater/profile.html', {
        'professor' : professor,
        'meta_score': meta_score,
        'word_cloud_entries': get_word_cloud_entries(prof_id),
    })


# review creation page for a professor of your choice
def review(request, prof_id):
    professor = get_object_or_404(Professor, pk=prof_id)
    return render(request, 'prof_rater/review.html', {
                  'professor' : professor })

def create_review(request, prof_id):
    professor = get_object_or_404(Professor, pk=prof_id)
    
    comment = request.POST.get('comments','')
    finalScore = request.POST.get('final_score','')
    courseNumber = request.POST.get('course_number','')
    courseSubject = request.POST.get('course_subject','')
    courseInterest = request.POST.get('interest_in_course','')

    #getting wordcloud entries
    phrase1 = request.POST.get('phrase_one','')
    phrase2 = request.POST.get('phrase_two','')
    phrase3 = request.POST.get('phrase_three','')

    if len(comment) == 0:
        return render(request, 'prof_rater/profile.html', {
            'professor': professor,
            'meta_score': calculate_metascore(prof_id),
            'word_cloud_entries': get_word_cloud_entries(prof_id),
            'error_message': "You need to comment before you can rate",
        })
    else:
        professor.review_set.create(comments = comment, 
                                    final_score = finalScore,
                                    #course_taken = courseTaken, 
                                    course_number = courseNumber,
                                    course_subject = courseSubject,
                                    interest_in_course = courseInterest,
                                    date_published = timezone.now())

        professor.wordcloud_set.create(phrase_one = phrase1,
                                       phrase_two = phrase2,
                                       phrase_three = phrase3)
    
        return HttpResponseRedirect(reverse('profile', args=(professor.id,)))


# This function calcuates the metascore of a professor
def calculate_metascore(prof_id):
    professor = Professor.objects.get(pk=prof_id)
    total_score = 0
    for review in professor.review_set.all():
            total_score += review.final_score

    if(total_score <= 0):
            return "n/a"
    else:
            max_score = professor.review_set.count() * 5
            meta_score = total_score/max_score * 5
            return "%.1f" % meta_score

# This function gets first 10 random wordcloud entries for a professor
def get_word_cloud_entries(prof_id):
    professor = Professor.objects.get(pk=prof_id)
    word_cloud_entries = professor.wordcloud_set.order_by('?')[:10]
    return word_cloud_entries
    

# This function calcuates the metascore of a department
def calculate_department_metascore(_course_subject):
    review_list = Review.objects.filter(course_subject=_course_subject)
    total_score = 0
    for review in review_list:
        total_score += review.final_score
    if(total_score <= 0):
            return "n/a"
    else:
            max_score = review_list.count() * 5
            meta_score = total_score/max_score * 5
            return "%.1f" % meta_score


# This function calcuates the metascore of a course
def calculate_course_metascore(_course_subject, _course_number):
    review_list = Review.objects.filter(course_subject=_course_subject).filter(course_number=_course_number)
    total_score = 0
    for review in review_list:
        total_score += review.final_score
    if(total_score <= 0):
            return "no ratings yet"
    else:
            max_score = review_list.count() * 5
            meta_score = total_score/max_score * 5
            return "%.1f" % meta_score



# This function returns a prof_list array that contains all unique professors
# retrieved from Professor objects with metascore calculated.
def get_prof_list():
    prof_list = Professor.objects.all()
    for p in prof_list:
        p.meta_score = calculate_metascore(p.pk)
    return prof_list

# This function returns a prof_list array that contains all professors who
# have taught this specific course
def get_prof_list_by_course(subject, number):
    # get all reviews about this specific course
    review_list = Review.objects.filter(course_subject=subject).filter(course_number=number)
    prof_list = []
    for review in review_list:
        if(prof_in_prof_list(prof_list, review.professor) == False):
            prof = review.professor
            prof_list.append(prof)
    return prof_list

# this function is to check whether this prof is inside the prof_list array
# called by get_prof_list_by_course()
def prof_in_prof_list(prof_list, prof):
    for p in prof_list:
        if (p == prof):
            return True
    return False

# This function returns a dept_list array that contains all unique departments
# retrieved from Department objects with metascore calculated.
def get_dept_list():
    dept_list = Department.objects.all()
    for d in dept_list:
        d.meta_score = calculate_department_metascore(d.code)
        d.review_set_count = len(Review.objects.filter(course_subject=d.code))
    return dept_list


# This function returns a course_list array that contains all unique courses
# retrieved from Review objects with metascore calculated.
def get_course_list():
    review_list = Review.objects.all()  # returns a dictionary
    course_list = []
    for review in review_list:
        if(course_in_course_list(course_list, review.course_subject, review.course_number) == False):
            course = Course(title = find_course_title_by_subject_and_number(review.course_subject, review.course_number),
                            subject = review.course_subject,
                            number = review.course_number,
                            meta_score = calculate_course_metascore(review.course_subject, review.course_number) )
            
            course.department_name = find_dept_name_by_code(review.course_subject)
            course.review_set_count = len(Review.objects.filter(course_subject=review.course_subject).filter(course_number=review.course_number))
            course_list.append(course)
    return course_list


# this function is to check whether this course is inside the course_list array
# called by get_course_list()
def course_in_course_list(list, subject, number):
    course_sub_and_num = subject + str(number)
    for c in list:
        c_sub_and_num = c.subject + str(c.number)
        if (course_sub_and_num.find( c_sub_and_num ) >= 0 ):
            return True
    return False


# This function takes a department code
# and returns the corresponding department name in string
def find_dept_name_by_code(_code):
    try:
        return get_object_or_404(Department, code=_code).name
    except Exception as e:
        return "Dept not found"


# This function takes the course subject and number
# and returns the corresponding course name in string
def find_course_title_by_subject_and_number(_subject, _number):
    try:
        return get_object_or_404(Course, subject=_subject).title
    except Exception as e:

prof_rater/templates/prof_rater/_index.html
{% comment %}
This is the index page using the include method. 
{% endcomment %}

{% include "prof_rater/header.html" %}

	<!-- jsko library -->
	<script type="text/javascript" src="http://knockoutjs.com/downloads/knockout-3.2.0.js"></script>


	<div id="content">

		<div class="search">
		    <h1>Search Criteria</h1>
		    <form action="#">
		    	Search by professor's name <br/>
		    	<input placeholder="e.g. Ted Kirkpatrick" type="search" name="q" data-bind="value: name_query, valueUpdate: 'keyup'" autocomplete="off">
		    </form>
			<form action="#">
		    	Search by department<br/>
		    	<input placeholder="e.g. Software Systems" type="search" name="r" data-bind="value: department_query, valueUpdate: 'keyup'" autocomplete="off">
		    </form>
		    <!-- TODO: Implement search by course -->
		    <form action="#" style="color:red;">
		    	Search by course<br/>
		    	<input placeholder="e.g. CMPT 470" type="search" name="s" autocomplete="off">
		    </form>
		</div>
		
		<div class="result">
		    <h1>Search Results</h1>
		    <ul data-bind='foreach: professorToShow'>
				<hr>
		    	<li>
		    		<!-- TODO: URL fix -->
		    		<a data-bind="attr: { href: id, title: id }">

			    		<span data-bind='text: first_name'></span>
			    		<span data-bind='text: last_name'></span>
			    	</a>
			    	(<span data-bind='text: department'></span>)
		    		<br/>

		    		<span data-bind='text: review_set_count'></span> student review(s).
		 			<br/>
		 			Meta Score: <span data-bind='text: meta_score'></span>
		    	</li>
		    </ul>
		    <hr>
	    </div>

	</div>




<!-- http://www.knockmeout.net/2011/04/utility-functions-in-knockoutjs.html -->
<!-- http://knockoutjs.com/examples/animatedTransitions.html -->
<!-- http://opensoul.org/2011/06/23/live-search-with-knockoutjs/ -->
<script>
	var ProfessorModel = function(professors) {
	    this.professors = ko.observableArray(professors);

	    this.addProf = function(pk, fn, ln, d, ms, rsc){
	    	this.professors.push({
				id: pk,
				first_name: fn,
				last_name: ln,
				department: d,
				meta_score: ms,
				review_set_count: rsc
			});
	    };

	    this.name_query = ko.observable(""),

	    this.department_query = ko.observable(""),

	    this.professorToShow = ko.pureComputed(function(){
	    	var input_name_query = this.name_query();
	    	var input_department_query = this.department_query();
	    	
	    	return ko.utils.arrayFilter(this.professors(), function(professor){
	    		var professor_full_name = professor.first_name + " " + professor.last_name;
	    		return (professor_full_name.toLowerCase().indexOf(input_name_query.toLowerCase()) >= 0) &&
					   (professor.department.toLowerCase().indexOf(input_department_query.toLowerCase())  >= 0);
	    	});
	    }, this);
	};
	 
	professorModel = new ProfessorModel([]);
	ko.applyBindings(professorModel);
</script>
{% for prof in prof_list %}
<script> professorModel.addProf("{{ prof.pk }}", "{{ prof.first_name }}", "{{ prof.last_name }}", "{{ prof.department }}", "{{ prof.meta_score }}", "{{ prof.review_set.count }}"); 
</script>
{% endfor %}


{% include "prof_rater/footer.html" %}

prof_rater/templates/prof_rater/base.html
{% comment %}
Note that base.html has <head></head> and <body></body>.
https://docs.djangoproject.com/en/dev/ref/templates/builtins/?from=olddocs#include
https://docs.djangoproject.com/en/dev/topics/templates/#template-inheritance
{% endcomment %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<title>{% block title %}Prof Rater by Team Delta 13{% endblock %}</title>

	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'style.css' %}" type="text/css" />

	<!-- JQuery library -->
	<script type="text/javascript" src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
	
</head>

<body>
	<header>
		<p><i><a href= "{% url 'index' %}">PROF RATER</a></i></p>

	</header>

	<div id="content">
	{% block content %}
	
	
	{% endblock %}
	</div>

	<footer>
		Team Delta 13 <br/>
		&copy; 2014 <br />
		All Rights Reserved
	</footer>

</body>
</html>

prof_rater/templates/prof_rater/course.html
{% extends "prof_rater/base.html" %}

{% comment %}
This is the course page. It contains the prof-list 
that belongs to this course
{% endcomment %}


{% block content %}

<div class="debug">

</div>



<h1 class="big center">{{h1}}</h1>
<div class="center"><small class="notes">You are searching within course <b>{{ h1 }}</b>.</small></div>

<div id="search-by-prof">
	<div class="search">
		{% include 'prof_rater/search-by-prof-form.html' %}
	</div>
	<div class="result">
	    {% include 'prof_rater/search-by-prof-result.html' %}
    </div>
</div>



{% comment %}
<ul>
{% for prof in prof_list %}
	<li>
		{{ prof.id }} {{ prof.first_name }} {{ prof.last_name }} - {{ prof.department }} 
		<br>

		Metascore: {{prof.meta_score}} ({{prof.review_set_count}} Reviews) 
	</li>
{% endfor %}
</ul>




				id: pk,
				first_name: fn,
				last_name: ln,
				department: d,
				meta_score: ms,
				review_set_count: rsc



    




<div class="course-list">
	<h1>Course list 2</h1>
	<ul>
	{% for course in course_list %}
		<li>{{ course.title }} - {{ course.subject }} {{ course.number }}
			<ul>
				<li>{{ course.department_name }}</li>
				<li>{{ course.meta_score }}</li>
				<li>{{ course.review_set_count }}</li>
			</ul>
		</li>
	{% endfor %}
	</ul>
</div>

<script type="text/javascript" src="http://knockoutjs.com/downloads/knockout-3.2.0.js"></script>
<div id="search-by-course">
	{% include 'prof_rater/search-by-course-form.html' %}
	{% include 'prof_rater/search-by-course-result.html' %}
</div>

<hr>
{% endcomment %}

{% endblock %}

prof_rater/templates/prof_rater/department.html
{% extends "prof_rater/base.html" %}

{% comment %}
This is the department page. It contains the course-list and prof-list 
that belongs to this department
{% endcomment %}


{% block content %}

<div class="debug">
	<h1>{{message}}</h1>
</div>

<h1 class="big center">{{ dept.code }} {{ dept.name }}</h1>
<div class="center"><small class="notes">You are searching within the <b>{{ dept.name }}</b> department.</small></div>

<div id="search-by-course">
	<div class="search">
		{% include 'prof_rater/search-by-course-form.html' %}
	</div>
	<div class="result">
		{% include 'prof_rater/search-by-course-result.html' %}
	</div>
</div>

<hr>

{% endblock %}

prof_rater/templates/prof_rater/footer.html
{% comment %}
Note that footer.html has </body>. <body> is in the header.html
{% endcomment %}


	<div id="footer">
		Team Delta 13 <br/>
		&copy; 2014 <br />
		All Rights Reserved
	</div>

</body>
</html>

prof_rater/templates/prof_rater/header.html
{% comment %}
Note that header.html has <head></head> and <body>.
</body> is in the footer.html
{% endcomment %}

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>Prof Rater by Team Delta 13</title>

<!-- google fonts -->

<!-- <link rel='stylesheet' href='/style.css' type='text/css'></link> -->
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'style.css'%}" type="text/css" />
<!-- TODO: use bootstrap for css later -->

</head>

<body>
	<div id="header">
		<p>header_banner_placeholder</p>
	</div>

prof_rater/templates/prof_rater/review.html
<head>
	<script type="text/javascript">
		var onloadCallback = function() {
			grecaptcha.render('html_element', {
				'sitekey' : '6Lfpgv4SAAAAACI5Qdk8cMfNbNhTtF4eQZNbXpcU'
			});
		};
    </script>
</head>
<h1>Rate {{ professor.first_name }}</h1>



{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'rate' professor.id %}" method="post">
{% csrf_token %}

<table>
	<tr>
		<td colspan="2">
			<small class="label">Comments: </small><br />
   			<textarea cols="250" id="id_comments" name="comments" rows="3"></textarea>
   			<br />
   			<small class="error-message-1" style="color:red;"></small>
    	</td>
	</tr>
	<tr>
		<td>
			<small class="label">Course Taken</small><br />
	        <input id = "id_course_subject" name="course_subject" type="text" value="" placeholder="CMPT" maxlength="4" size="4"/><br />
	        <small class="notes">Course subject</small><br />
	        <small class="error-message-2" style="color:red;"></small>

		</td>
		<td>
			<small class="label"> . </small><br />
    		<input id = "id_course_number" name="course_number" value="" placeholder="470" size="3" type="number" min="100" max="999"/><br />
	        <small class="notes">Course number</small><br />
	        <small class="error-message-3" style="color:red;"></small>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<small class="label">Write three phrases that best describes {{ professor.first_name }}{{ professor.last_name }}:</small><br />
			<input id = "id_phrase_one" name="phrase_one" type="text" value="" placeholder="e.g hard to follow" maxlength="20" size="20"/>
		    <input id = "id_phrase_two" name="phrase_two" type="text" value="" placeholder="e.g hard assignments" maxlength="20" size="20"/>
		    <input id = "id_phrase_three" name="phrase_three" type="text" value="" placeholder="e.g not nice" maxlength="20" size="20"/>
		</td>
	</tr>
	<tr>
		<td>
			<small class="label">Final Score:</small><br />
    		<input type="range" min="1" max="5" step="1" id="id_scoreSlider" name="final_score" value="1" /><br />
    		<small class="notes" id="score_label" for="id_scoreSlider">Absolutely Terrible!</small>
		</td>

		<td>
		    <small class="label">Interest in Course</small><br />
		    <input type="range" min="1" max="5" step="1" id="id_interestSlider" name="interest_in_course" value="1" /><br />
		    <small class="notes" id="interest_label" for="id_interestSlider">Don't care..</small>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<div id="html_element"></div>
			<br />
		</td>
	</tr>
	<tr>
		<td>
		<div class="rate-button" style="width:100%;" onclick="validate();">
			Rate {{ professor.first_name }} {{ professor.last_name }}
		</div>
		{% comment %}
		invisible button, triggered only if the form is validated.
		{% endcomment %}
		<input class="submit-button" type="submit" value="Rate {{ professor.first_name }}" style="display:none;"/>
		</td>
	</tr>
</table>
</form>

<script src="https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit" async defer></script>

<script type="text/javascript">
function validate(){
	var comment = $( "#id_comments" ).val();
	var course_subject = $( "#id_course_subject" ).val();
	var course_number = $( "#id_course_number" ).val();

	var error_message = ["", "", ""];

	if(comment=="") error_message[0] = "You must enter some comments.";
	
	if(course_subject.length <3 || course_subject.length>4) error_message[1] = "Course subject must be 3 - 4 characters.";
	
	if(course_number < 100 || course_number >999) error_message[2] = "Invalid course number.";
	

	if(error_message[0] != "" || error_message[1] !="" || error_message[2] != "" ){
		$( ".error-message-1" ).html(error_message[0]);
		$( ".error-message-2" ).html(error_message[1]);
		$( ".error-message-3" ).html(error_message[2]);
		var top = $('.review-form').position().top;
		$(window).scrollTop( top );

	}
	else{
		//isValidate, submit
		var upperCrsSubject =  $( "#id_course_subject" ).val().toUpperCase();
		$( "#id_course_subject" ).val(upperCrsSubject);
		$( ".submit-button" ).click();
	}
}
</script>

<script type="text/javascript">
	$( document ).ready(function() {
								 
		$( "#id_scoreSlider" ).change(function() {
			if( $( this ).val() >= 1 && $( this ).val() < 1.9 ){
				$( "#score_label" ).html("Absolutely Terrible!");
			}
			if( $( this ).val() >= 2 && $( this ).val() < 2.9 ){
				$( "#score_label" ).html("Meh..");
			}
			if( $( this ).val() >= 3 && $( this ).val() < 3.9 ){
				$( "#score_label" ).html("Alright..");
			}
			if( $( this ).val() >= 4 && $( this ).val() < 4.9 ){
				$( "#score_label" ).html("Great!");
			}
			if( $( this ).val() >= 5 && $( this ).val() < 5.9 ){
				$( "#score_label" ).html("Awesome!");
			}
			
		})
		
		$( "#id_interestSlider" ).change(function() {
			if( $( this ).val() >= 1 && $( this ).val() < 1.9 ){
				$( "#interest_label" ).html("Don't care..");
			}
			if( $( this ).val() >= 2 && $( this ).val() < 2.9 ){
				$( "#interest_label" ).html("Hmm..");
			}
			if( $( this ).val() >= 3 && $( this ).val() < 3.9 ){
				$( "#interest_label" ).html("Cool course");
			}
			if( $( this ).val() >= 4 && $( this ).val() < 4.9 ){
				$( "#interest_label" ).html("So interesting!");
			}
			if( $( this ).val() >= 5 && $( this ).val() < 5.9 ){
				$( "#interest_label" ).html("I Love it!");
			}
			
		})
	});
</script>

prof_rater/templates/prof_rater/search-by-course-form.html
 <form action="#">
 	<table>
	 	<tr><td>
		<input placeholder="e.g. CMPT470" type="search" name="s" data-bind="value: course_search_query, valueUpdate: 'keyup'" autocomplete="off">
		
		<small class="notes">Alternatively, you can enter a course title or a department name.</small>
		</td></tr>
	</table>
</form> 

prof_rater/templates/prof_rater/search-by-dept-form.html
<form action="#"><table>
 	<tr><td>
		<input placeholder="e.g. Computing Science" type="search" name="s" data-bind="value: department_search_query, valueUpdate: 'keyup'" autocomplete="off">

		<small class="notes">Alternatively, you can enter a course code. For example, <b>CMPT</b> for Computing Science.</small>	
	</td></tr>
</table></form> 

prof_rater/templates/prof_rater/search-by-prof-form.html
<form action="#"><table>
	<tr><td>
		<small class="label">Name: </small><br />
		<input placeholder="e.g. Ted Kirkpatrick" type="search" name="q" data-bind="value: prof_name_query, valueUpdate: 'keyup'" autocomplete="off">
	</td></tr>
	
	<tr><td>
		<small class="label">Department: </small><br />
		<input placeholder="e.g. Software Systems" type="search" name="r" data-bind="value: prof_department_query, valueUpdate: 'keyup'" autocomplete="off">
	</td></tr>
</table></form>